Ap16WebApplication/Ap16WebApplication/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Ap16WebApplication.Controllers
{
    public class HomeController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {
            return View();
        }
    }
}

Ap16WebApplication/Ap16WebApplication/Controllers/TaskController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Ap16WebApplication.ServiceAPI;

namespace Ap16WebApplication.Controllers
{
    public class TaskController : Controller
    {
        private readonly IRestServiceApi _serviceApi;

        public TaskController(IRestServiceApi serviceApi)
        {
            _serviceApi = serviceApi;
        }


        [HttpPost]
        public async Task<ActionResult> ShowTasks()
        {
            var model = await _serviceApi.GetTaskDetailsAsync();
            return View("ShowTasks", model);
        }

        // GET: Task/Create
        public ActionResult AddTask()
        {
            return View();
        }

        // POST: Task/Create
        [HttpPost]
        public ActionResult AddTask(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("ShowTasks");
            }
            catch
            {
                return View();
            }
        }

        // GET: Task/Edit/5
        public async Task<ActionResult> EditTask(int id)
        {
            var model = await _serviceApi.GetTaskDetailsAsync();

            return View("EditTask", model.SingleOrDefault(x => x.Id==id));
        }

        // POST: Task/Edit/5
        [HttpPost]
        public ActionResult EditTask(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("ShowTasks");
            }
            catch
            {
                return View();
            }
        }

        // GET: Task/Delete/5
        public async Task<ActionResult> DeleteTask(int id)
        {
            var model = await _serviceApi.GetTaskDetailsAsync();

            return View("DeleteTask", model.SingleOrDefault(x => x.Id == id));
        }

        // POST: Task/Delete/5
        [HttpPost]
        public ActionResult DeleteTask(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("ShowTasks");
            }
            catch
            {
                return View();
            }
        }
    }
}

Ap16WebApplication/Ap16WebApplication/Views/Home/Index.cshtml
@model dynamic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
    <div>
        <button type="button" id="searchButton">Search</button>
    </div>
<div id="divTest">
</div>
</body>
</html>

<script>
    $('#searchButton').click(function() {
        $.post(
            '@Url.Action("ShowTasks", "Task")',
        function(data) {
            $('#divTest').html(data);
        }
    );
    });
</script>

Ap16WebApplication/Ap16WebApplication/Views/Main/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<div>
    <form>

        <div>
            <button type="button" id="searchButton">open Tasks</button>
        </div>
        
        <div id="divTest">
        </div>

    </form>
</div>
</body>
</html>
<script>
    
    
    $('#searchButton').click(function () {

        $(this).button("loading").delay().queue(function () {

            var searchTextBoxValue = $('#searchTextBox').val();

            if (searchTextBoxValue) {
                $.post(
                    '@Url.Action("ShowTasks", "Task"))',
                    function(data) {
                        if (data) {
                            $('#divTest').html(data);
                        }
                    });
            }  
              
            $(this).button("reset");
            $(this).dequeue();
        });


    });
</script>

Ap16WebApplication/Ap16WebApplication/Views/Task/AddTask.cshtml
@model DTO.TaskDetailsDTO

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Task</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ShowTasks")
</div>

Ap16WebApplication/Ap16WebApplication/Views/Task/DeleteTask.cshtml
@model DTO.TaskDetailsDTO

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Task</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div>
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ShowTasks")
        </div>
    }
</div>

Ap16WebApplication/Ap16WebApplication/Views/Task/EditTask.cshtml
@model DTO.TaskDetailsDTO

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Task</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ShowTasks")
</div>

Ap16WebApplication/Ap16WebApplication/Views/Task/ShowTasks.cshtml
@model IEnumerable<DTO.TaskDetailsDTO>

 
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditTask", new { id=item.Id }) |
            @Html.ActionLink("Add Task", "AddTask") |
            @Html.ActionLink("Delete", "DeleteTask", new { id=item.Id })
        </td>
    </tr>
}

</table>